In [14]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [15]:
import numpy as np
import pandas as pd

In [16]:
for_modeling_result=pd.read_csv('for_modeling_result.csv')
for_modeling_result.head()

,자치구,기간,합계,살인,강도,강간강제추행,절도,폭력,금액(천원/명),상대격차(배),절대격차(천원/명),이사간 인구 수,지하철 역 수
0,강남구,2014,8851,13,37,512,3895,4394,446.0,0.90,-52.1,115906,29
1,종로구,2014,5021,3,12,226,2272,2508,608.0,1.22,109.8,24191,15
2,마포구,2014,5740,4,22,265,2763,2686,497.3,1.00,-0.8,68853,22
3,중구,2014,5231,6,13,221,2576,2415,702.8,1.41,204.7,20105,23
4,중랑구,2014,5353,11,14,163,2390,2775,532.0,1.07,33.8,69157,14

In [44]:
# statsmodels 모델에서 컬럼명에 공백을 허용하지않아 컬럼명 변경....
for_modeling_rename=for_modeling_result.rename(columns={'이사간 인구 수':'이사인구',	'지하철 역 수':'지하철역수','금액(천원/명)':'인당복지예산'})
for_modeling_rename.head()

,자치구,기간,합계,살인,강도,강간강제추행,절도,폭력,인당복지예산,상대격차(배),절대격차(천원/명),이사인구,지하철역수
0,강남구,2014,8851,13,37,512,3895,4394,446.0,0.90,-52.1,115906,29
1,종로구,2014,5021,3,12,226,2272,2508,608.0,1.22,109.8,24191,15
2,마포구,2014,5740,4,22,265,2763,2686,497.3,1.00,-0.8,68853,22
3,중구,2014,5231,6,13,221,2576,2415,702.8,1.41,204.7,20105,23
4,중랑구,2014,5353,11,14,163,2390,2775,532.0,1.07,33.8,69157,14

In [33]:
# 다중선형회귀 적합
model = smf.ols(formula = '합계 ~ 인당복지예산 + 이사인구 + 지하철역수', data = for_modeling_rename)
result = model.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     합계   R-squared:                       0.517
Model:                            OLS   Adj. R-squared:                  0.502
Method:                 Least Squares   F-statistic:                     34.25
Date:                Tue, 03 Dec 2019   Prob (F-statistic):           3.88e-15
Time:                        12:40:11   Log-Likelihood:                -820.92
No. Observations:                 100   AIC:                             1650.
Df Residuals:                      96   BIC:                             1660.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   3435.0732    790.867      4.343      0.000    1865.214    5004.932
인당복지예산        -1.8037      0.943     -1.913      0.059      -3.675       0.068
이사인구           0.0247      0.005      4.912      0.000       0.015       0.035
지하철역수         67.7401     14.117      4.798      0.000      39.717      95.763
==============================================================================
Omnibus:                        2.535   Durbin-Watson:                   2.478
Prob(Omnibus):                  0.282   Jarque-Bera (JB):                1.888
Skew:                          -0.161   Prob(JB):                        0.389
Kurtosis:                       2.409   Cond. No.                     5.69e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.69e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# 다중회귀모형
y = 3435.0732 - 1.8037 * 인당복지예산 + 0.0247 * 이사인구 + 67.7401 * 지하철역수